// This file was auto-generated by Fern from our API Definition.

export const InsionEnvironment = {
    Default: "https://api.insion.co",
} as const;

export type InsionEnvironment = typeof InsionEnvironment.Default;
