// This file was auto-generated by Fern from our API Definition.

export const InsionClientEnvironment = {
    Default: "https://api.insion.co",
} as const;

export type InsionClientEnvironment = typeof InsionClientEnvironment.Default;
