// This file was auto-generated by Fern from our API Definition.

export type Content =
    /**
     * Text content to moderate. */
    | string
    | {
          text: string;
          imageUrls?: string[] | undefined;
          externalUrls?: string[] | undefined;
      };
