// This file was auto-generated by Fern from our API Definition.

export interface CreateAppealResponse {
    data: CreateAppealResponse.Data;
}

export namespace CreateAppealResponse {
    export interface Data {
        id: string;
        actionStatus: Data.ActionStatus | null;
        actionStatusCreatedAt: string | null;
        createdAt: string;
        updatedAt: string;
        appealUrl: string | null;
    }

    export namespace Data {
        export const ActionStatus = {
            Compliant: "Compliant",
            Suspended: "Suspended",
            Banned: "Banned",
        } as const;
        export type ActionStatus = (typeof ActionStatus)[keyof typeof ActionStatus];
    }
}
