// This file was auto-generated by Fern from our API Definition.

export interface ErrorResponse {
    error: ErrorResponse.Error_;
}

export namespace ErrorResponse {
    export interface Error_ {
        message: string;
    }
}
