// This file was auto-generated by Fern from our API Definition.

export const GetApiV1RecordsRequestStatus = {
    Compliant: "Compliant",
    Flagged: "Flagged",
} as const;
export type GetApiV1RecordsRequestStatus =
    (typeof GetApiV1RecordsRequestStatus)[keyof typeof GetApiV1RecordsRequestStatus];
