// This file was auto-generated by Fern from our API Definition.

export const GetApiV1UsersRequestStatus = {
    Compliant: "Compliant",
    Suspended: "Suspended",
    Banned: "Banned",
} as const;
export type GetApiV1UsersRequestStatus = (typeof GetApiV1UsersRequestStatus)[keyof typeof GetApiV1UsersRequestStatus];
