// This file was auto-generated by Fern from our API Definition.

import type * as InsionClient from "../index.js";

export interface IngestUserResponse extends InsionClient.SuccessResponse {
    /** Insion user ID. */
    id: string;
}
