// This file was auto-generated by Fern from our API Definition.

import type * as Insion from "../index.js";

export interface IngestRecordResponse extends Insion.SuccessResponse {
    /** Insion record ID. */
    id: string;
    /** Insion moderation ID when moderation was queued; otherwise null. */
    moderation: string | null;
    /** Insion user ID when a user was provided. */
    user?: string | undefined;
}
