// This file was auto-generated by Fern from our API Definition.

import type * as Insion from "../index.js";

export interface IngestUserResponse extends Insion.SuccessResponse {
    /** Insion user ID. */
    id: string;
}
