// This file was auto-generated by Fern from our API Definition.

/**
 * Custom metadata. Keys must be at most 40 characters and cannot include [ or ]. Values must be serializable, at most 500 characters, and the object can contain at most 50 keys.
 */
export type Metadata = Record<string, unknown>;
