// This file was auto-generated by Fern from our API Definition.

export interface ModerateResponse {
    /** Insion record ID. */
    id: string;
    /** Moderation status. */
    status: ModerateResponse.Status;
    /** Insion moderation ID. */
    moderation: string;
    /** Insion user ID when a user was provided. */
    user?: string | undefined;
    message: string;
    /** Deprecated. True when status is Flagged. */
    flagged: boolean;
    /** IDs of rules that matched the record. */
    categoryIds: string[];
}

export namespace ModerateResponse {
    /** Moderation status. */
    export const Status = {
        Compliant: "Compliant",
        Flagged: "Flagged",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
