// This file was auto-generated by Fern from our API Definition.

import type * as Insion from "../index.js";

export interface RecordInput {
    /** Your unique identifier for the record. */
    clientId: string;
    /** URL for the original content. */
    clientUrl?: string | undefined;
    /** Name or title of the record. */
    name: string;
    /** Type of record, such as post, comment, or message. */
    entity: string;
    content: Insion.Content;
    metadata?: Insion.Metadata | undefined;
    user?: Insion.UserInput | undefined;
}
