// This file was auto-generated by Fern from our API Definition.

import type * as InsionClient from "../index.js";

export interface Record_ {
    id: string;
    clientId: string;
    clientUrl?: (string | null) | undefined;
    name: string;
    entity: string;
    protected: boolean;
    metadata?: InsionClient.Metadata | undefined;
    createdAt: string;
    updatedAt: string;
    moderationStatus?: (Record_.ModerationStatus | null) | undefined;
    moderationStatusCreatedAt?: (string | null) | undefined;
    moderationPending: boolean;
    moderationPendingCreatedAt?: (string | null) | undefined;
    /** Associated Insion user ID. */
    user?: (string | null) | undefined;
}

export namespace Record_ {
    export const ModerationStatus = {
        Compliant: "Compliant",
        Flagged: "Flagged",
    } as const;
    export type ModerationStatus = (typeof ModerationStatus)[keyof typeof ModerationStatus];
}
