// This file was auto-generated by Fern from our API Definition.

import type * as Insion from "../index.js";

export interface UserInput {
    /** Your unique identifier for the user. */
    clientId: string;
    /** URL for the user's profile. */
    clientUrl?: string | undefined;
    /** The user's Stripe account ID. */
    stripeAccountId?: string | undefined;
    /** The user's email address. */
    email?: string | undefined;
    /** The user's name. */
    name?: string | undefined;
    /** The user's username. */
    username?: string | undefined;
    /** Whether the user is protected from automated moderation actions. */
    protected?: boolean | undefined;
    metadata?: Insion.Metadata | undefined;
}
