// This file was auto-generated by Fern from our API Definition.

import type * as Insion from "../index.js";

export interface User {
    id: string;
    clientId: string;
    clientUrl?: (string | null) | undefined;
    email?: (string | null) | undefined;
    name?: (string | null) | undefined;
    username?: (string | null) | undefined;
    protected: boolean;
    metadata?: Insion.Metadata | undefined;
    createdAt: string;
    updatedAt: string;
    actionStatus?: (User.ActionStatus | null) | undefined;
    actionStatusCreatedAt?: (string | null) | undefined;
    appealUrl: string | null;
}

export namespace User {
    export const ActionStatus = {
        Compliant: "Compliant",
        Suspended: "Suspended",
        Banned: "Banned",
    } as const;
    export type ActionStatus = (typeof ActionStatus)[keyof typeof ActionStatus];
}
