// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         clientId: "clientId"
 *     }
 */
export interface DeleteApiV1IngestRequest {
    /** Your unique identifier for the record. */
    clientId: string;
}
