// This file was auto-generated by Fern from our API Definition.

import type * as InsionClient from "../../index.js";

/**
 * @example
 *     {}
 */
export interface GetApiV1RecordsRequest {
    /** Maximum number of items to return. */
    limit?: number;
    /** Return items after this Insion ID. Cannot be used with ending_before. */
    starting_after?: string;
    /** Return items before this Insion ID. Cannot be used with starting_after. */
    ending_before?: string;
    /** Filter by your record identifier. */
    clientId?: string;
    /** Filter by Insion user ID. */
    user?: string;
    /** Filter by record entity. */
    entity?: string;
    /** Filter by moderation status. */
    status?: InsionClient.GetApiV1RecordsRequestStatus;
}
