// This file was auto-generated by Fern from our API Definition.

import type * as InsionClient from "../../index.js";

/**
 * @example
 *     {}
 */
export interface GetApiV1UsersRequest {
    /** Maximum number of items to return. */
    limit?: number;
    /** Return items after this Insion ID. Cannot be used with ending_before. */
    starting_after?: string;
    /** Return items before this Insion ID. Cannot be used with starting_after. */
    ending_before?: string;
    /** Filter by your user identifier. */
    clientId?: string;
    /** Filter by user email. */
    email?: string;
    /** Filter by user action status. */
    status?: InsionClient.GetApiV1UsersRequestStatus;
    /** Filter by Insion user ID. */
    user?: string;
}
