// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         recordId: "recordId"
 *     }
 */
export interface GetApiV1RecordsRecordIdRequest {
    /** Insion record ID. */
    recordId: string;
}
