// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         userId: "userId"
 *     }
 */
export interface GetApiV1UsersUserIdRequest {
    /** Insion user ID. */
    userId: string;
}
