// This file was auto-generated by Fern from our API Definition.

import type * as Insion from "../../index.js";

/**
 * @example
 *     {
 *         clientId: "clientId",
 *         name: "name",
 *         entity: "entity",
 *         content: "content"
 *     }
 */
export interface ModerateRequest extends Insion.RecordInput {
    /** Moderate without persisting the record's name or content, or the user's email, name, or username. */
    passthrough?: boolean;
}
