// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         userId: "userId",
 *         text: "text"
 *     }
 */
export interface PostApiV1UsersUserIdCreateAppealRequest {
    /** Insion user ID. */
    userId: string;
    /** The appeal message. */
    text: string;
}
